### 1. Registrar un nuevo usuario
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "Jose Alfredo",
  "email": "jose@correo.com",
  "password": "MiPasswordSeguro123"
}

###

### 2. Iniciar Sesión (Login)
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "jose@correo.com",
  "password": "MiPasswordSeguro123"
}

###

### 3. Crear un Formulario (Ejemplo: Ficha de Proyecto)
POST http://localhost:5000/api/projects
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMTRkYTVmOWY4NjNmNWFiNWYyYjA5MyIsImVtYWlsIjoiam9zZUBjb3JyZW8uY29tIiwiaWF0IjoxNzc5NzUxODkyLCJleHAiOjE3Nzk4MzgyOTJ9.ijik80Xfcod3eYDKRnd3oAYxP70jkr_4YR_MHx-9-X0


{
  "title": "Sistema de Inventario para el Laboratorio 2 de la UPTAEB",
  "description": "Desarrollo de una plataforma web para la gestión y control automatizado del hardware donado al laboratorio de informática.",
  "type": "Ficha",
  "metadata": {
    "lineaInvestigacion": "Sistemas de Información y Software Libre",
    "comunidad": "UPTAEB Laboratorio 2"
  }
}

###

### 4. Obtener mis proyectos registrados
GET http://localhost:5000/api/projects
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMTRkYTVmOWY4NjNmNWFiNWYyYjA5MyIsImVtYWlsIjoiam9zZUBjb3JyZW8uY29tIiwiaWF0IjoxNzc5NzUxODkyLCJleHAiOjE3Nzk4MzgyOTJ9.ijik80Xfcod3eYDKRnd3oAYxP70jkr_4YR_MHx-9-X0